In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
ref_file = "/lustre/scratch/shared-folders/bio_project/shuxian/gbft/mg/rna_202507/RNAGym/fitness/reference_sheet_final.csv"
metric_dir = "/lustre/scratch/shared-folders/bio_project/shuxian/gbft/mg/rna_202507/RNAGym/fitness_prediction/metric"

ref = pd.read_csv(ref_file)
ref.head()

,DMS_ID,TITLE,AUTHOR,YEAR,RNA_TYPE,RNA_TYPE_GRANULAR,RAW_CONSTRUCT_SEQ,ASSAY_DESCRIPTION,PDB_STRUCTURE,RFAM_LINK,WT_DMS_SCORE,Notes
0,Andreasson_2020_ribozyme,Comprehensive sequence-to-function mapping of ...,Andreasson,2020,Ribozyme,Ribozyme riboswitch,AUAAAAGCGCCAGAACUACAGAAAUGUAGUUGACGAGGAGGAGGUU...,Deep mutational scanning assay measuring the s...,PDB 2Z75,https://rfam.org/family/glmS,0.071215256,NaN
1,Beck_2022_ribozyme,Predicting higher-order mutational effects in ...,Beck,2022,Ribozyme,Ribozyme,GGGGGCCACAGCAGAAGCGUUCACGUCGCGGCCCCUGUCAGAUUCU...,Deep mutational scanning assay measuring the s...,NaN,https://rfam.org/family/CPEB3_ribozyme,/,NaN
2,Domingo_2018_tRNA,Pairwise and higher-order genetic interactions...,Domingo,2018,tRNA,tRNA,GUUCCGUUGGCGUAAUGGUAACGCGUCUCCCUCCUAAGGAGAAGAC...,Deep mutational scanning assay measuring the f...,NaN,https://rfam.org/family/tRNA,0,NaN
3,Guy_2014_tRNA,Identification of the determinants of tRNA fun...,Guy,2014,tRNA,tRNA,CUCUCGGUAGCCAAGUUGGUUUAAGGCGCAAGACUUUAAUUUAUCA...,Deep mutational scanning assay measuring the s...,PDB 1EHZ,https://rfam.org/family/tRNA,1,NaN
4,Janzen_2022_fam1a1_ribozyme,Emergent properties as by-products of prebioti...,Janzen,2022,Ribozyme,Fam1A.1 aminoacylation ribozyme,GGGAAUGGAUCCACAUCUACGAAUUCCUACUUCAAACAAUCGGUCU...,Deep mutational scanning assay measuring the s...,NaN,NaN,104.650357,NaN

In [3]:
models = ["aido_rna_650m_cds", "aido_rna_650m"] #["aido_rna_1b600m_cds", "aido_rna_1b600m"]
methods = ["wt-marginals"]  #"masked-marginals",

for model in models:
    for method in methods:
        print(f"{model}-{method}")
        metric_path = os.path.join(metric_dir, f"{model}-{method}.csv")
        df = pd.read_csv(metric_path)
        merged = pd.merge(ref, df, left_on="DMS_ID", right_on="dms_id", how="left")
        print("RNA TYPE")
        mean_df = merged.groupby("RNA_TYPE")["spearman"].mean().reset_index()
        print(mean_df)
        mean_df = merged.groupby("RNA_TYPE")["auc"].mean().reset_index()
        print(mean_df)
        mean_df = merged.groupby("RNA_TYPE")["mcc"].mean().reset_index()
        print(mean_df)
        print("mRNA coding species")
        mean_df = merged[merged["RNA_TYPE"] == "mRNA-coding"].groupby("ASSAY_DESCRIPTION")["spearman"].mean().reset_index()
        print(mean_df)
        print("-------------")

aido_rna_650m_cds-wt-marginals
RNA TYPE
        RNA_TYPE  spearman
0        Aptamer  0.148123
1       Ribozyme  0.206624
2    mRNA-coding  0.195621
3  mRNA-splicing  0.131919
4           tRNA  0.499710
        RNA_TYPE       auc
0        Aptamer  0.556975
1       Ribozyme  0.600674
2    mRNA-coding  0.598310
3  mRNA-splicing  0.585137
4           tRNA  0.747668
        RNA_TYPE       mcc
0        Aptamer  0.104049
1       Ribozyme  0.143228
2    mRNA-coding  0.141061
3  mRNA-splicing  0.152782
4           tRNA  0.369535
mRNA coding species
  ASSAY_DESCRIPTION  spearman
0               EUK  0.286687
1             HUMAN  0.210260
2              PROK  0.168769
3             VIRUS  0.155881
-------------
aido_rna_650m-wt-marginals
RNA TYPE
        RNA_TYPE  spearman
0        Aptamer  0.189671
1       Ribozyme  0.155789
2    mRNA-coding  0.079932
3  mRNA-splicing  0.147182
4           tRNA  0.426537
        RNA_TYPE       auc
0        Aptamer  0.579737
1       Ribozyme  0.574000
2    mRNA-coding  0.543051
3  mRNA-splicing  0.564413
4           tRNA  0.714495
        RNA_TYPE       mcc
0        Aptamer  0.123868
1       Ribozyme  0.108304
2    mRNA-coding  0.069851
3  mRNA-splicing  0.128943
4           tRNA  0.317940
mRNA coding species
  ASSAY_DESCRIPTION  spearman
0               EUK  0.086885
1             HUMAN  0.064877
2              PROK  0.098437
3             VIRUS  0.070458
-------------

In [8]:
merged

,DMS_ID,TITLE,AUTHOR,YEAR,RNA_TYPE,RNA_TYPE_GRANULAR,RAW_CONSTRUCT_SEQ,ASSAY_DESCRIPTION,PDB_STRUCTURE,RFAM_LINK,WT_DMS_SCORE,Notes,Unnamed: 0,dms_id,spearman,auc,mcc
0,Andreasson_2020_ribozyme,Comprehensive sequence-to-function mapping of ...,Andreasson,2020,Ribozyme,Ribozyme riboswitch,AUAAAAGCGCCAGAACUACAGAAAUGUAGUUGACGAGGAGGAGGUU...,Deep mutational scanning assay measuring the s...,PDB 2Z75,https://rfam.org/family/glmS,0.071215256,NaN,0,Andreasson_2020_ribozyme,0.053816,0.529292,0.008989
1,Beck_2022_ribozyme,Predicting higher-order mutational effects in ...,Beck,2022,Ribozyme,Ribozyme,GGGGGCCACAGCAGAAGCGUUCACGUCGCGGCCCCUGUCAGAUUCU...,Deep mutational scanning assay measuring the s...,NaN,https://rfam.org/family/CPEB3_ribozyme,/,NaN,1,Beck_2022_ribozyme,0.097140,0.547988,0.069181
2,Domingo_2018_tRNA,Pairwise and higher-order genetic interactions...,Domingo,2018,tRNA,tRNA,GUUCCGUUGGCGUAAUGGUAACGCGUCUCCCUCCUAAGGAGAAGAC...,Deep mutational scanning assay measuring the f...,NaN,https://rfam.org/family/tRNA,0,NaN,2,Domingo_2018_tRNA,0.364555,0.674474,0.241198
3,Guy_2014_tRNA,Identification of the determinants of tRNA fun...,Guy,2014,tRNA,tRNA,CUCUCGGUAGCCAAGUUGGUUUAAGGCGCAAGACUUUAAUUUAUCA...,Deep mutational scanning assay measuring the s...,PDB 1EHZ,https://rfam.org/family/tRNA,1,NaN,3,Guy_2014_tRNA,0.391586,0.688279,0.286807
4,Janzen_2022_fam1a1_ribozyme,Emergent properties as by-products of prebioti...,Janzen,2022,Ribozyme,Fam1A.1 aminoacylation ribozyme,GGGAAUGGAUCCACAUCUACGAAUUCCUACUUCAAACAAUCGGUCU...,Deep mutational scanning assay measuring the s...,NaN,NaN,104.650357,NaN,4,Janzen_2022_fam1a1_ribozyme,0.047064,0.519950,0.041474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,RDRP_I33A0_Li_2023,Deep mutational scanning reveals the functiona...,Li,2023,mRNA-coding,mRNA-coding,ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCACAAA...,VIRUS,-,-,-,NaN,65,RDRP_I33A0_Li_2023,0.015798,0.501046,0.009914
66,R1AB_SARS2_Flynn_2022,Comprehensive fitness landscape of SARS-CoV-2 ...,Flynn,2022,mRNA-coding,mRNA-coding,TCGGGGTTTCGCAAAATGGCGTTTCCGTCCGGCAAAGTGGAAGGTT...,VIRUS,-,-,-,NaN,66,R1AB_SARS2_Flynn_2022,0.018932,0.509382,0.012052
67,A0A2Z5U3Z0_9INFA_Doud_2016,Accurate Measurement of the Effects of All Ami...,Doud,2016,mRNA-coding,mRNA-coding,ATGAAGGCAAAACTACTGGTCCTGTTATATGCATTTGTAGCTACAG...,VIRUS,-,-,-,NaN,67,A0A2Z5U3Z0_9INFA_Doud_2016,0.051487,0.525320,0.032384
68,TAT_HV1BR_Fernandes_2016,Functional Segregation of Overlapping Genes in...,Fernandes,2016,mRNA-coding,mRNA-coding,ATGGAACCTGTGGACCCCCGCTTGGAACCTTGGAAACACCCTGGCT...,VIRUS,-,-,-,NaN,68,TAT_HV1BR_Fernandes_2016,0.084883,0.549460,0.086873
69,CAPSD_AAV2S_Sinai_2021,Generative AAV capsid diversification by laten...,Sinai,2021,mRNA-coding,mRNA-coding,ATGGCTGCCGATGGCTATCTTCCAGATTGGCTCGAGGACACTCTCT...,VIRUS,-,-,-,NaN,69,CAPSD_AAV2S_Sinai_2021,0.064572,0.518480,0.015971